name: Install Dependencies
description: Install dependencies
runs:
    using: composite
    steps:
        -   name: Install Homebrew Dependencies
            shell: bash
            run: |
                brew install gnu-sed
        -   name: Checkout Rust-Lightning and LDK-C-Bindings git
            shell: bash
            run: |
                echo `pwd`
                mkdir -p ./bindings/artifacts/bin
                git clone --branch 2022-07-109-java-bindings https://github.com/TheBlueMatt/rust-lightning ./bindings/artifacts/rust-lightning
                git clone --branch v0.0.109.0 https://github.com/lightningdevkit/ldk-c-bindings ./bindings/artifacts/ldk-c-bindings
        -   name: Install Rust, required targets
            shell: bash
            run: |
                rustup toolchain install nightly
                rustup target add aarch64-apple-darwin aarch64-apple-ios x86_64-apple-ios
                rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
        -   name: Load Cache
            uses: actions/cache@v3
            with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        -   name: Generate C Bindings
            shell: bash
            run: |
                export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
                pushd bindings/artifacts/ldk-c-bindings
                ./genbindings.sh ../rust-lightning true
                popd
        -   name: Generate Swift Bindings
            shell: bash
            run: |
                python3 ./
            env:
                LDK_SWIFT_GENERATOR_INPUT_HEADER_PATH: bindings/artifacts/ldk-c-bindings/lightning-c-bindings/include/lightning.h
