name: XCFramework from sequential Python script
permissions:
    contents: read
    statuses: read
    pull-requests: read
    actions: read
    checks: write
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    generate-sequential:
        name: Build libldks, build xcarchives, and combine into xcframework
        runs-on: macos-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
            LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
        steps:
            -   name: Configure Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                uses: ./.github/actions/install-dependencies
            -   name: Generate XCFramework
                uses: ./.github/actions/generate-xcframework
            -   name: Zip Xcframework
                run: |
                    ditto -c -k --sequesterRsrc /Users/runner/work/ldk-swift/ldk-swift/bindings/bin/release/LDKFramework.xcframework LDKFramework.xcframework.zip
            -   name: Upload Framework Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: LDKFramework
                    path: LDKFramework.xcframework.zip
