name: Generate XCFramework Workflow
permissions:
    contents: read
    statuses: read
    pull-requests: read
    actions: read
    checks: write
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    build:
        name: Generate XCFramework job
        runs-on: macos-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
            LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
        steps:
            -   name: Configure Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                uses: ./.github/actions/install-dependencies
            -   name: Build binaries
                run:
                    python3 ./src/scripts/build_bulk_libldks.py
            -   name: Generate xcframework
                run:
                    python3 ./src/scripts/generate_xcframework.py
