name: Release Framework
permissions:
    contents: write
    statuses: read
    pull-requests: read
    actions: read
    checks: write
on:
    workflow_dispatch:
        inputs:
            tags:
                description: 'Test scenario tags'
                required: true
                type: boolean
    push:
        tags:
            - "*"

jobs:
    generate-xcframework:
        name: Generate XCFramework
        runs-on: macos-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
            LDK_C_BINDINGS_BASE: /Users/runner/work/ldk-swift/ldk-swift/bindings/artifacts/ldk-c-bindings
        steps:
            -   name: Configure Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                uses: ./.github/actions/install-dependencies
            -   name: Generate XCFramework
                uses: ./.github/actions/generate-xcframework
            -   name: Zip Xcframework
                run: |
                    ditto -c -k --sequesterRsrc /Users/runner/work/ldk-swift/ldk-swift/bindings/bin/release/LDKFramework.xcframework LDKFramework.xcframework.zip
            -   name: Upload Framework Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: LDKFramework.xcframework.zip
                    path: LDKFramework.xcframework.zip
    release:
        name: Publish Release
        runs-on: ubuntu-latest
        needs: [ generate-xcframework ]
        steps:
            -   name: Download Framework Artifact
                uses: actions/download-artifact@v3
                with:
                    name: LDKFramework.xcframework.zip
            -   name: Create Release
                uses: softprops/action-gh-release@v1
                with:
                    files: LDKFramework.xcframework.zip
